### PR TITLE
Migrate to extended image

### PR DESCRIPTION
**Pull request by itssidhere**
Refactored to use extended image and removed flutter_spinkit and cached_network_image. However, I would like you to review the emoji page

### CODE REVIEW

**Comment by itssidhere** [comment]
Kindly fix the ratio of sticker tiles

**Comment by itssidhere** [comment]
I think the animated switcher is causing some performance issues, can you confirm it?

**Review by bazookon — APPROVED** [review]
Thanks

**Comment by itssidhere** [comment]
@bazookon have you checked for any issues?

**Comment by bazookon** [comment]
I changed horizontal items for emojis(5) and sticker(3) following instagram guidlines for giphy. are you agree?

**Comment by itssidhere** [comment]
@bazookon  Ok, I agree. But I am not sure why are we following Instagram guidelines. We should give this option to user also to choose the cross axis count

**Comment by bazookon** [comment]
> @bazookon  Ok, I agree. But I am not sure why are we following Instagram guidelines. We should give this option to user also to choose the cross axis count

Ok, i'll add that options, thanks.

**Pull request merged**
